title: Slugger Space
description: "A place to share my thoughts, poems, and projects."
baseurl: "/nyyshaaa"        # the repo name, so links resolve
url: "https://nyyshaaa.github.io"


theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "sunrise" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Tell Minimal Mistakes to load our extra CSS
defaults:
  -
    scope:
      path: ""         # all files
    values:
      custom_css: "/assets/css/custom.css"


# ── COLLECTIONS ────────────────────────────────────────────────
collections:
  poems:
    output: true
    permalink: /poems/:path/
  projects:
    output: true
    permalink: /projects/:path/
  projects:
    output: true
    permalink: /blogs/:path/
  projects:
    output: true
    permalink: /sololeveling/:path/
  projects:
    output: true
    permalink: /science/:path/
  projects:
    output: true
    permalink: /ideas/:path/
  projects:
    output: true
    permalink: /star-dreams/:path/
  

footer:
  links: false

# ── COLOR OVERRIDES ────────────────────────────────────────────

header_background: "#336699"
header_text:       "#ffffff"
link_color:        "#f0c040"
