name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read      # needed to checkout your code
  pages: write        # needed to push to Gh‑Pages
  id-token: write     # needed by configure-pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby & Bundler cache
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'    # or whatever exact version you pinned
          bundler-cache: true      # runs `bundle install` and caches gems

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build site with Jekyll
        run: |
          bundle exec jekyll build \
            --config _config.yml \
            --destination _site
        env:
          JEKYLL_ENV: production

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
